"""empty message

Revision ID: 0879e0f3010e
Revises: acc96a2aadcf
Create Date: 2024-02-07 18:09:28.322460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0879e0f3010e'
down_revision: Union[str, None] = 'acc96a2aadcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pdfs', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('pdfs', 'object_key',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pdfs', 'object_key',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('pdfs', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###
