"""change the status column type to enum

Revision ID: 0b17cc0bdb9b
Revises: 1a3fcb3d7eae
Create Date: 2024-03-05 16:14:02.990567

"""

# Standard Library
from typing import Sequence, Union

# Third Party Library
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b17cc0bdb9b"
down_revision: Union[str, None] = "1a3fcb3d7eae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "images",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "pending",
            "preprocessing",
            "preprocessed",
            "preprocessing_timedout",
            "preprocessing_failed",
            "matching_calculation",
            "matching_calculation_timedout",
            "matching_calculation_failed",
            "matching_calculation_success",
            "differential_calculation",
            "differential_calculation_timedout",
            "differential_calculation_no_differences_found",
            "differential_calculation_failed",
            "differential_calculation_not_enough_matches",
            "completed",
            "failed",
            "canceled",
            "retry",
            name="status",
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "jsons",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "pending",
            "preprocessing",
            "preprocessed",
            "preprocessing_timedout",
            "preprocessing_failed",
            "matching_calculation",
            "matching_calculation_timedout",
            "matching_calculation_failed",
            "matching_calculation_success",
            "differential_calculation",
            "differential_calculation_timedout",
            "differential_calculation_no_differences_found",
            "differential_calculation_failed",
            "differential_calculation_not_enough_matches",
            "completed",
            "failed",
            "canceled",
            "retry",
            name="status",
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "matchings",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "pending",
            "preprocessing",
            "preprocessed",
            "preprocessing_timedout",
            "preprocessing_failed",
            "matching_calculation",
            "matching_calculation_timedout",
            "matching_calculation_failed",
            "matching_calculation_success",
            "differential_calculation",
            "differential_calculation_timedout",
            "differential_calculation_no_differences_found",
            "differential_calculation_failed",
            "differential_calculation_not_enough_matches",
            "completed",
            "failed",
            "canceled",
            "retry",
            name="status",
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "pages",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "pending",
            "preprocessing",
            "preprocessed",
            "preprocessing_timedout",
            "preprocessing_failed",
            "matching_calculation",
            "matching_calculation_timedout",
            "matching_calculation_failed",
            "matching_calculation_success",
            "differential_calculation",
            "differential_calculation_timedout",
            "differential_calculation_no_differences_found",
            "differential_calculation_failed",
            "differential_calculation_not_enough_matches",
            "completed",
            "failed",
            "canceled",
            "retry",
            name="status",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pages",
        "status",
        existing_type=sa.Enum(
            "pending",
            "preprocessing",
            "preprocessed",
            "preprocessing_timedout",
            "preprocessing_failed",
            "matching_calculation",
            "matching_calculation_timedout",
            "matching_calculation_failed",
            "matching_calculation_success",
            "differential_calculation",
            "differential_calculation_timedout",
            "differential_calculation_no_differences_found",
            "differential_calculation_failed",
            "differential_calculation_not_enough_matches",
            "completed",
            "failed",
            "canceled",
            "retry",
            name="status",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "matchings",
        "status",
        existing_type=sa.Enum(
            "pending",
            "preprocessing",
            "preprocessed",
            "preprocessing_timedout",
            "preprocessing_failed",
            "matching_calculation",
            "matching_calculation_timedout",
            "matching_calculation_failed",
            "matching_calculation_success",
            "differential_calculation",
            "differential_calculation_timedout",
            "differential_calculation_no_differences_found",
            "differential_calculation_failed",
            "differential_calculation_not_enough_matches",
            "completed",
            "failed",
            "canceled",
            "retry",
            name="status",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "jsons",
        "status",
        existing_type=sa.Enum(
            "pending",
            "preprocessing",
            "preprocessed",
            "preprocessing_timedout",
            "preprocessing_failed",
            "matching_calculation",
            "matching_calculation_timedout",
            "matching_calculation_failed",
            "matching_calculation_success",
            "differential_calculation",
            "differential_calculation_timedout",
            "differential_calculation_no_differences_found",
            "differential_calculation_failed",
            "differential_calculation_not_enough_matches",
            "completed",
            "failed",
            "canceled",
            "retry",
            name="status",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "images",
        "status",
        existing_type=sa.Enum(
            "pending",
            "preprocessing",
            "preprocessed",
            "preprocessing_timedout",
            "preprocessing_failed",
            "matching_calculation",
            "matching_calculation_timedout",
            "matching_calculation_failed",
            "matching_calculation_success",
            "differential_calculation",
            "differential_calculation_timedout",
            "differential_calculation_no_differences_found",
            "differential_calculation_failed",
            "differential_calculation_not_enough_matches",
            "completed",
            "failed",
            "canceled",
            "retry",
            name="status",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
