"""empty message

Revision ID: 17b3f0496dea
Revises: 4f7d0b8e9580
Create Date: 2024-03-07 11:59:26.062440

"""

# Standard Library
from typing import Sequence, Union

# Third Party Library
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17b3f0496dea"
down_revision: Union[str, None] = "4f7d0b8e9580"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("versions", "description", existing_type=sa.VARCHAR(length=512), nullable=False)
    op.alter_column("versions", "object_key", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("versions", "object_key", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("versions", "description", existing_type=sa.VARCHAR(length=512), nullable=True)
    # ### end Alembic commands ###
