"""empty message

Revision ID: 3c78460cec51
Revises: 50fdc7cf30e8
Create Date: 2024-02-10 02:41:55.454554

"""

# Standard Library
from typing import Sequence, Union

# Third Party Library
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c78460cec51"
down_revision: Union[str, None] = "50fdc7cf30e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("pdfs", "thumbnail", existing_type=sa.VARCHAR(length=256), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("pdfs", "thumbnail", existing_type=sa.VARCHAR(length=256), nullable=True)
    # ### end Alembic commands ###
