"""change index column to local_index and global_index in page table

Revision ID: 4f7d0b8e9580
Revises: 17dd088ff3a8
Create Date: 2024-03-06 11:27:02.952710

"""

# Standard Library
from typing import Sequence, Union

# Third Party Library
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f7d0b8e9580"
down_revision: Union[str, None] = "17dd088ff3a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pages", sa.Column("local_index", sa.Integer(), nullable=False))
    op.add_column("pages", sa.Column("global_index", sa.Integer(), nullable=False))
    op.drop_column("pages", "index")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pages", sa.Column("index", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column("pages", "global_index")
    op.drop_column("pages", "local_index")
    # ### end Alembic commands ###
