"""empty message

Revision ID: 50fdc7cf30e8
Revises: 0879e0f3010e
Create Date: 2024-02-09 16:18:17.397447

"""

# Standard Library
from typing import Sequence, Union

# Third Party Library
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50fdc7cf30e8"
down_revision: Union[str, None] = "0879e0f3010e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "thumbnail")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("thumbnail", sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
