"""empty message

Revision ID: 8ec3ce737b04
Revises: 7fab3e45e848
Create Date: 2024-02-07 16:20:22.552388

"""

# Standard Library
from typing import Sequence, Union

# Third Party Library
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ec3ce737b04"
down_revision: Union[str, None] = "7fab3e45e848"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("title", sa.String(length=256), nullable=False))
    op.add_column("projects", sa.Column("description", sa.String(length=512), nullable=True))
    op.add_column("projects", sa.Column("thumbnail", sa.String(length=256), nullable=True))
    op.drop_column("projects", "name")
    op.drop_column("projects", "team_id")
    op.add_column("users", sa.Column("status", sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "status")
    op.add_column(
        "projects", sa.Column("team_id", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "projects", sa.Column("name", sa.VARCHAR(length=256), autoincrement=False, nullable=False)
    )
    op.drop_column("projects", "thumbnail")
    op.drop_column("projects", "description")
    op.drop_column("projects", "title")
    # ### end Alembic commands ###
