"""empty message

Revision ID: 94984805c1d1
Revises: 17b3f0496dea
Create Date: 2024-03-21 10:33:56.989663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94984805c1d1'
down_revision: Union[str, None] = '17b3f0496dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('original_object_key', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'original_object_key')
    # ### end Alembic commands ###
