"""empty message

Revision ID: a96e2e7baf53
Revises: 94984805c1d1
Create Date: 2024-03-21 11:03:09.674884

"""

# Standard Library
from typing import Sequence, Union

# Third Party Library
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a96e2e7baf53"
down_revision: Union[str, None] = "94984805c1d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "matchings", "score", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "matchings", "score", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    # ### end Alembic commands ###
