"""empty message

Revision ID: b6083fb048d8
Revises: e130237cc163
Create Date: 2024-02-07 16:37:29.690129

"""

# Standard Library
from typing import Sequence, Union

# Third Party Library
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6083fb048d8"
down_revision: Union[str, None] = "e130237cc163"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("projects", "description", existing_type=sa.VARCHAR(length=512), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("projects", "description", existing_type=sa.VARCHAR(length=512), nullable=True)
    # ### end Alembic commands ###
