"""empty message

Revision ID: d8e30bd98f83
Revises: dc06fc8ec453
Create Date: 2024-02-14 15:17:55.212668

"""

# Standard Library
from typing import Sequence, Union

# Third Party Library
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8e30bd98f83"
down_revision: Union[str, None] = "dc06fc8ec453"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pages",
        "index",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="index::integer",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pages",
        "index",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        postgresql_using="index::text",
    )
    # ### end Alembic commands ###
