# api config
APP_API_VERSION: "v1"
APP_API_CORS_ALLOWED_ORIGINS: "*"

# lambda powertools config
POWERTOOLS_SERVICE_NAME: "api-dev"
POWERTOOLS_LOG_LEVEL: "DEBUG"
POWERTOOLS_DEV: true
POWERTOOLS_DEBUG: true
POWERTOOLS_TRACE_MIDDLEWARES: true
POWERTOOLS_TRACE_DISABLED: false

# SQLAlchemy config
SQLALCHEMY_ECHO_SQL: false

# AWS RDS config
AWS_RDS_DATABASE_URL: postgresql+psycopg2://aska:aska@localhost:5433/app

# AWS VPC
vpc:
  securityGroupIds:
    - sg-0e04a593ba030f3b2 # allow postgresql
  subnetIds:
    - subnet-07490af99721de89b # app-private-subnet-ap-northeast-1a-dev
    - subnet-0b813d5d3c902f887 # app-private-subnet-ap-northeast-1c-dev
